### PR TITLE
#22 set vi name handles underscores

### LINKED ISSUE #22: Wanted: Handle underscores in filename when using "Set Icon to VI Name"
As mentioned above, if your filename has underscores instead of spaces, the "Set Icon to VI Name" is unusable. Would be great if it could treat an underscore the same as a space when parsing filename for the icon text.
VI Name

### PR DESCRIPTION
**Pull request by JayKayAce**
Changes made:
- [x] Added tests for Split Text into Words.vi
- [x] Added functionality to Split Text into Words.vi
- [x] Changed scope of the Split Text into Words.vi to community scope.
- [x] Added friendship with the test library for calling community VIs.

### CODE REVIEW

**Review by svelderrainruiz — CHANGES_REQUESTED** [review]
I tried opening your lvproj on 2 different systems using LV21 x86  and got the same issue.

image

Make sure you fix the package dependencies warning. Did you tried running "Prepare LV to Use Icon Editor Source.vi" before making your changes? if unsure, try running it, if it gives you a popup, that means you havent run it yet on that repo before starting to make your changes.

This may not be the only issue that this PR has, but i am hopeful that fixing this would make other issues go away too.

**Review by svelderrainruiz — CHANGES_REQUESTED** [review]
I see you removed project items that were missing. We need this to happen, but need this issue to be addressed by its own github issue, since if we somehow decide to revert the contents of this PR, this would bring back the dependency issue that you fixed.

Please revert this change, it will be addressed on the following github issue that has its own branch.
/issues/45

**Comment by JayKayAce** [comment]
Thanks for the feedback. 
I have reverted the project file, and re-added the test library. 
Looking over the changes I think the Package dependency was created by mistake when I opened the project file via JKI Dragon, but I am not entirely sure. It should at least be fixed now.
Further more when inspecting the project file I see many changes in the URIs for the listed files, could this be because I am editing the project in LV2024Q3@32Bit?

**Comment by JayKayAce** [comment]
image
This missing file is now reverted again

**Comment by svelderrainruiz** [comment]
> Thanks for the feedback. I have reverted the project file, and re-added the test library. Looking over the changes I think the Package dependency was created by mistake when I opened the project file via JKI Dragon, but I am not entirely sure. It should at least be fixed now. Further more when inspecting the project file I see many changes in the URIs for the listed files, could this be because I am editing the project in LV2024Q3@32Bit?

I am also getting many changes on the project file. Not sure what it is, but does needs to get fixed on a separate issue.
I am using LV2021 SP1 X86 to edit the source.
There are no indications on readme.md of not using the LV2024's feature of saving the source into a previous version, but it would be good to understand if LV2024 is what caused you this issue, so that the readme.md can be updated with an indication to use only LV2021 IDE

**Comment by svelderrainruiz** [comment]
@JayKayAce i cant seem to find the issue for this pull request. Would you mind making one?

**Comment by svelderrainruiz** [comment]
@JayKayAce  nevermind.. i think i found it, please confirm this is the one /issues/22

**Comment by JayKayAce** [comment]
that is correct this is linked to issue #22

**Review by svelderrainruiz — APPROVED** [review]

**Pull request merged**
